<?php

return [
    'plugin' => [
        'name' => 'Google Photos plugin',
        'description' => 'This plugin allows to display albums from your Google Photos (Picasa) account'
    ],

    'permissions' => [
        'access_settings' => 'Access Google Photos plugin settings',
        'tab' => 'Google Photos',
    ],

    'settings' => [
        'menuEntry' => [
            'label' => 'Google Photos',
            'description' => 'Settings for Google Photos plugin'
        ],
        'fields' => [
            'oAuthLabel' => 'GooglePhotos Authentication',
            'oAuthSignIn' => 'Sign in',
            'oAuthSignOut' => 'Sign out',
            'oAuthAppWarning' => 'You need additional configuration steps',
            'oAuthAppWarningMessage' => 'Please setup an OAuth app in order to use this plugin on a non-localhost domain (<a href="https://octobercms.com/plugin/inetis-googlephotos" target="_blank">see prerequisites section of the install guide</a>). Clicking the sign-in button now will most likely return an error.',
            'signOutConfirm' => 'Are you sure you want to revoke your authorization token?',
            'cacheDurationLabel' => 'Cache duration (minutes)',
            'hiddenAlbumsLabel' => 'Hidden albums',
            'hiddenAlbumsDescription' => 'You can specify here the albums you want to be ignored. For example, you may want to hide the "Auto Backup" album generated by Picasa.',
            'hiddenAlbumLabel' => 'Album name or ID'
        ]
    ],

    'component' => [
        'albums' => [
            'name' => 'Google Photos albums list',
            'description' => 'Display all albums of the Google Photos account'
        ],

        'album' => [
            'name' => 'Google Photos album',
            'description' => 'Display one album of the Google Photos account'
        ],

        'fields' => [
            'albumPageTitle' => 'Album Page',
            'albumPageDescription' => 'The page that displays the detail of an album',
            'albumIdTitle' => 'Album ID',
            'albumIdDescription' => 'ID of the Google Photos album to show',
            'thumbHeightTitle' => 'Height',
            'thumbHeightDescription' => 'Maximum height of generated thumbnails. Let empty for auto height',
            'thumbWidthTitle' => 'Width',
            'thumbWidthDescription' => 'Maximum width of generated thumbnails. Let empty for auto width',
            'shouldCropTitle' => 'Crop',
            'shouldCropDescription' => 'Whether to crop thumbnails to fit exactly specified size or just resize them',
            'pageSizeTitle' => 'Page size',
            'pageSizeDescription' => 'Number of items to display per page (0 to disable pagination)',
            'currentPageTitle' => 'Current page',
            'currentPageDescription' => 'The parameter to use as current page (starting at 1)',

            'optionYes' => 'Yes',
            'optionNo' => 'No',
        ],

        'fieldsGroups' => [
            'pagination' => 'Pagination',
            'thumbnails' => 'Thumbnails'
        ]
    ],

    'messages' => [
        'csrfMismatch' => 'CSRF token mismatch',
        'authSuccess' => 'Authenticated successfully',
        'revokeSuccess' => 'Access revoked successfully',
        'revokeError' => 'Error trying to revoke access: :error'
    ]
];
